<?php

namespace Database\Seeders;

use App\Models\Militaire;
use App\Models\Armee;
use Illuminate\Database\Seeder;

class MilitairesSeeder extends Seeder
{
    public function run(): void
    {
        // Récupérer les IDs des armées
        $armees = Armee::pluck('id', 'nom')->toArray();

        $militaires = [
            [
                'matricule' => 'MIL-2020-001',
                'nom' => 'Traoré',
                'prenoms' => 'Moussa',
                'date_naissance' => '1990-05-15',
                'lieu_naissance' => 'Bamako',
                'nom_pere' => 'Traoré',
                'prenoms_pere' => 'Mamadou',
                'nom_mere' => 'Diarra',
                'prenoms_mere' => 'Fatoumata',
                'grade_id' => 5,
                'unite' => '1ère Compagnie',
                'adresse' => 'Bamako, Quartier 123',
                'telephone' => '223 12 34 56 78',
                'statut' => 'Actif',  // Valeur simple
                'genre' => 'Masculin',
                'armee_id' => $armees['Armée de Terre'] ?? null,
                'armee' => 'Armée de Terre',
                'type_personnel' => 'militaire',
            ],
            [
                'matricule' => 'MIL-2020-002',
                'nom' => 'Coulibaly',
                'prenoms' => 'Amadou',
                'date_naissance' => '1992-08-20',
                'lieu_naissance' => 'Kati',
                'nom_pere' => 'Coulibaly',
                'prenoms_pere' => 'Moussa',
                'nom_mere' => 'Keita',
                'prenoms_mere' => 'Aminata',
                'grade_id' => 3,
                'unite' => '2ème Compagnie',
                'adresse' => 'Kati, Camp Militaire',
                'telephone' => '223 87 65 43 21',
                'statut' => 'Actif',
                'genre' => 'Masculin',
                'armee_id' => $armees['Armée de Terre'] ?? null,
                'armee' => 'Armée de Terre',
                'type_personnel' => 'militaire',
            ],
            [
                'matricule' => 'MIL-2021-003',
                'nom' => 'Keita',
                'prenoms' => 'Ibrahim',
                'date_naissance' => '1995-03-10',
                'lieu_naissance' => 'Ségou',
                'nom_pere' => 'Keita',
                'prenoms_pere' => 'Souleymane',
                'nom_mere' => 'Traoré',
                'prenoms_mere' => 'Mariam',
                'grade_id' => 2,
                'unite' => '3ème Compagnie',
                'adresse' => 'Ségou, Quartier Administratif',
                'telephone' => '223 44 55 66 77',
                'statut' => 'Inactif',  // Valeur simple
                'genre' => 'Masculin',
                'armee_id' => $armees['Garde Nationale'] ?? null,
                'armee' => 'Garde Nationale',
                'type_personnel' => 'militaire',
            ],
            [
                'matricule' => 'MIL-2019-004',
                'nom' => 'Diallo',
                'prenoms' => 'Fatoumata',
                'date_naissance' => '1988-12-01',
                'lieu_naissance' => 'Bamako',
                'nom_pere' => 'Diallo',
                'prenoms_pere' => 'Amadou',
                'nom_mere' => 'Coulibaly',
                'prenoms_mere' => 'Aissata',
                'grade_id' => 6,
                'unite' => 'État-Major Général',
                'adresse' => 'Bamako, ACI 2000',
                'telephone' => '223 99 88 77 66',
                'statut' => 'Actif',
                'genre' => 'Féminin',
                'armee_id' => $armees['État-Major Général'] ?? null,
                'armee' => 'État-Major Général',
                'type_personnel' => 'militaire',
            ],
            [
                'matricule' => 'MIL-2021-005',
                'nom' => 'Koné',
                'prenoms' => 'Seydou',
                'date_naissance' => '1996-07-25',
                'lieu_naissance' => 'Koulikoro',
                'nom_pere' => 'Koné',
                'prenoms_pere' => 'Mamadou',
                'nom_mere' => 'Sissoko',
                'prenoms_mere' => 'Kadiatou',
                'grade_id' => 1,
                'unite' => 'Bataillon de Kati',
                'adresse' => 'Kati, Quartier Est',
                'telephone' => '223 33 22 11 00',
                'statut' => 'Inactif',  // Valeur simple
                'genre' => 'Masculin',
                'armee_id' => $armees['Armée de Terre'] ?? null,
                'armee' => 'Armée de Terre',
                'type_personnel' => 'militaire',
            ],
            [
                'matricule' => 'MIL-2018-006',
                'nom' => 'Sangaré',
                'prenoms' => 'Oumar',
                'date_naissance' => '1985-11-15',
                'lieu_naissance' => 'Mopti',
                'nom_pere' => 'Sangaré',
                'prenoms_pere' => 'Bakary',
                'nom_mere' => 'Dembélé',
                'prenoms_mere' => 'Awa',
                'grade_id' => 7,
                'unite' => 'Direction du Génie Militaire',
                'adresse' => 'Mopti, Centre-Ville',
                'telephone' => '223 55 44 33 22',
                'statut' => 'Actif',
                'genre' => 'Masculin',
                'armee_id' => $armees['Direction du Génie Militaire'] ?? null,
                'armee' => 'Direction du Génie Militaire',
                'type_personnel' => 'militaire',
            ],
            [
                'matricule' => 'MIL-2022-007',
                'nom' => 'Maïga',
                'prenoms' => 'Aïssata',
                'date_naissance' => '1993-04-08',
                'lieu_naissance' => 'Gao',
                'nom_pere' => 'Maïga',
                'prenoms_pere' => 'Oumar',
                'nom_mere' => 'Diallo',
                'prenoms_mere' => 'Mariam',
                'grade_id' => 3,
                'unite' => 'Gendarmerie Nationale',
                'adresse' => 'Gao, Quartier Nord',
                'telephone' => '223 77 66 55 44',
                'statut' => 'Actif',
                'genre' => 'Féminin',
                'armee_id' => $armees['Gendarmerie Nationale'] ?? null,
                'armee' => 'Gendarmerie Nationale',
                'type_personnel' => 'militaire',
            ],
            [
                'matricule' => 'MIL-2017-008',
                'nom' => 'Doumbia',
                'prenoms' => 'Mamadou',
                'date_naissance' => '1980-09-30',
                'lieu_naissance' => 'Kayes',
                'nom_pere' => 'Doumbia',
                'prenoms_pere' => 'Souleymane',
                'nom_mere' => 'Coulibaly',
                'prenoms_mere' => 'Aminata',
                'grade_id' => 11,
                'unite' => 'Direction du Service de Santé',
                'adresse' => 'Kayes, Quartier Sud',
                'telephone' => '223 66 77 88 99',
                'statut' => 'Retraité',  // Valeur simple
                'genre' => 'Masculin',
                'armee_id' => $armees['Direction du Service de Santé des Armées'] ?? null,
                'armee' => 'Direction du Service de Santé des Armées',
                'type_personnel' => 'militaire',
            ],
            [
                'matricule' => 'MIL-2023-009',
                'nom' => 'Camara',
                'prenoms' => 'Boubacar',
                'date_naissance' => '1998-02-14',
                'lieu_naissance' => 'Bamako',
                'nom_pere' => 'Camara',
                'prenoms_pere' => 'Bakary',
                'nom_mere' => 'Sissoko',
                'prenoms_mere' => 'Fatoumata',
                'grade_id' => 1,
                'unite' => 'Direction des Transmissions',
                'adresse' => 'Bamako, Faladiè',
                'telephone' => '223 88 77 66 55',
                'statut' => 'Actif',
                'genre' => 'Masculin',
                'armee_id' => $armees['Direction des Transmissions'] ?? null,
                'armee' => 'Direction des Transmissions',
                'type_personnel' => 'militaire',
            ],
            [
                'matricule' => 'MIL-2020-010',
                'nom' => 'Sidibé',
                'prenoms' => 'Kadiatou',
                'date_naissance' => '1991-06-18',
                'lieu_naissance' => 'Bamako',
                'nom_pere' => 'Sidibé',
                'prenoms_pere' => 'Mamadou',
                'nom_mere' => 'Diallo',
                'prenoms_mere' => 'Aissata',
                'grade_id' => 5,
                'unite' => 'Police Nationale',
                'adresse' => 'Bamako, Hippodrome',
                'telephone' => '223 99 00 11 22',
                'statut' => 'Actif',
                'genre' => 'Féminin',
                'armee_id' => $armees['Police Nationale'] ?? null,
                'armee' => 'Police Nationale',
                'type_personnel' => 'militaire',
            ],
            [
                'matricule' => 'MIL-2024-011',
                'nom' => 'Diakité',
                'prenoms' => 'Moussa',
                'date_naissance' => '1997-11-22',
                'lieu_naissance' => 'Sikasso',
                'nom_pere' => 'Diakité',
                'prenoms_pere' => 'Alassane',
                'nom_mere' => 'Konaté',
                'prenoms_mere' => 'Mariam',
                'grade_id' => 4,
                'unite' => 'DRHA',
                'adresse' => 'Bamako, DRHA',
                'telephone' => '223 45 67 89 01',
                'statut' => 'Actif',
                'genre' => 'Masculin',
                'armee_id' => $armees['DRHA'] ?? null,
                'armee' => 'DRHA',
                'type_personnel' => 'militaire',
            ],
        ];

        foreach ($militaires as $militaire) {
            Militaire::create($militaire);
        }
    }
}